@startuml

class AppProgramas {
  +main(args : String[]) : void
}

class Cadena {
  -nombre : String
  -listaProgramas : ArrayList<Programa>

  +Cadena(nombre : String)
  +getNombre() : String
  +setNombre(nombre : String)
  +getListaProgramas() : ArrayList<Programa>
  +insertarPrograma(p : Programa) : void
  +eliminarPrograma(p : Programa) : void
  +toString() : String
}

class Programa {
  -nombre : String
  -cadena : Cadena
  -temporadas : int
  -listaEmpleados : ArrayList<Empleado>
  -listaInvitados : ArrayList<Invitado>
  -director : Empleado

  +Programa(nombre : String, cadena : Cadena, nombreDirector : String)
  +getNombre() : String
  +setNombre(nombre : String)
  +getCadena() : Cadena
  +setCadena(cadena : Cadena)
  +getTemporadas() : int
  +setTemporadas(temporadas : int)
  +getListaEmpleados() : ArrayList<Empleado>
  +getListaInvitados() : ArrayList<Invitado>
  +insertarEmpleado(nombre : String, cargo : String, director : Empleado) : void
  +insertarInvitado(nombre : String, profesion : String, temporada : int) : void

  +invitadosTemporada(temporada : int) : void
  +vecesInvitado(nombre : String) : int
  +rastrearInvitado(nombre : String) : void
  +buscarInvitado(nombre : String) : boolean
  +invitadoAntes(nombre : String, otroPrograma : Programa) : void

  +toString() : String
}

class Empleado {
  -id : String
  -nombre : String
  -cargo : String
  -director : Empleado

  +Empleado(nombre : String, cargo : String, director : Empleado)
  +getId() : String
  +getNombre() : String
  +setNombre(nombre : String)
  +getCargo() : String
  +setCargo(cargo : String)
  +getDirector() : Empleado
  +setDirector(director : Empleado)
  +toString() : String
}

class Invitado {
  -nombre : String
  -profesion : String
  -fecha_visita : LocalDate
  -temporada : int

  +Invitado(nombre : String, profesion : String, temporada : int)
  +getNombre() : String
  +setNombre(nombre : String)
  +getProfesion() : String
  +setProfesion(profesion : String)
  +getFecha_visita() : LocalDate
  +setFecha_visita(fecha : LocalDate)
  +getTemporada() : int
  +setTemporada(temporada : int)
  +toString() : String
}

AppProgramas --> Cadena
AppProgramas --> Programa

Cadena "1" o-- "0..*" Programa : contiene
Programa "1" --> "1" Cadena : pertenece

Programa "1" *-- "0..*" Empleado : composición
Programa "1" *-- "0..*" Invitado : composición

Empleado "0..1" --> "1" Empleado : director

@enduml
